### PR TITLE
values-sk: updated a couple of strings

### PR DESCRIPTION
**Pull request by Adman**
Signed-off-by: Adrian Matejov <a.matejov@centrum.sk>

### CODE REVIEW

**Comment by hzsweers** [comment]
Thanks! Is there someone else you could have review these? I unfortunately cannot for obvious reasons :)

**Comment by Adman** [comment]
@hzsweers probably not

**Comment by hzsweers** [comment]
Then I can't merge this

**Comment by Adman** [comment]
@hzsweers alright, will try to make someone from slovakia review it

**Comment by mato157** [comment]
I checked Adman's review and the translation is OK.

**Comment by hzsweers** [comment]
A real account please.

**Comment by Adman** [comment]
@hzsweers If you are so stubborn then close this pull request and I will no more translate this... That's my friend's account who joined github 2 years ago...

**Comment by hzsweers** [comment]
I'm sorry but it's just a pretty big red flag when you say you can't find anyone else to review, then show up 30min later with a random other account that has no name or history.

I will close this then since you're unwilling to abide by the rules in our `CONTRIBUTING.md`.

**Pull request closed without merging**
