### PR TITLE
Support building in Docker

### PR DESCRIPTION
**Pull request by neuhalje**
`build_in_docker.sh` creates a Docker VM, mounts the current directory in it, and builds PocketHub.

### CODE REVIEW

**Comment by hzsweers** [comment]
Why would we need/want this?

**Comment by neuhalje** [comment]
The main advantage is that it completely isolates the build environment. E.g. installing android dev tools, etc. At the very least it is an executable documentation on how to set up the build environment.

**Comment by hzsweers** [comment]
Would rather just use the sdkmanager plugin. Sorry but not going to merge this, it's not something we want to maintain support for considering it's no something most developers would use.

**Comment by CrazyBay** [comment]
I don't kouw！


发自 网易邮箱大师
在2015年12月29日 01:05，Zac Sweers 写道:

Why would we need/want this?

**Pull request closed without merging**
