### PR TITLE
Set github oauth values via simple gradle properties

### LINKED ISSUE #884: Build Failing - Encryption key not generated.
I am not sure how to handle this error 

```0.01s$ openssl aes-256-cbc -K $encrypted_7e1c958561a2_key -iv $encrypted_7e1c958561a2_iv -in github.properties.enc -out github.properties -d```
```iv undefined```
```The command "openssl aes-256-cbc -K $encrypted_7e1c958561a2_key -iv $encrypted_7e1c958561a2_iv -in github.properties.enc -out github.properties -d" failed and exited with 1 during .```

there was a change added about 10 days ago and it seems to have taken the build out. If someone could put into the README how to handle this it would be really helpful. I think it has to do with this. http://docs.travis-ci.com/user/encrypting-files/

### PR DESCRIPTION
**Pull request by larsgrefer**
Let's use simple gradle properties as described here (https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_properties_and_system_properties) in order to set the github specific oauth values

fixes #884

### CODE REVIEW

**Comment by larsgrefer** [comment]
travis fails because of #886

**Comment by M13Kd** [comment]
I'll add a dummy value. ☆M13Kd

**Comment by fadils** [comment]
@Meisolsson is this similar to what you want to do?

**Comment by fadils** [comment]
LGTM. Thanks @larsgrefer.

**Pull request merged**
