### PR TITLE
Show warnings if oauth values aren't set

### LINKED ISSUE #916: 404 error when initial login is attempted
I've just compiled and installed ee3e4a38ee2acc6addd775ad52d577751593c986 as a fresh new user (uninstalled my very old version from when it was an official GitHub app). After attempting to log in from the start up screen, I enter my GitHub details and then get stuck on a GitHub 404 page. I can't proceed any further than this.

It looks to be server-side, but perhaps the app is requesting a page or API endpoint that no longer exists.

Tested on a Nexus 4, with 5.1.1.

### PR DESCRIPTION
**Pull request by larsgrefer**
Show some warnings so things like #916 don't happen.

resolves #916

### CODE REVIEW

**Comment by StefMa** [comment]
Looks good. But is this a real thing what we need?

**Comment by larsgrefer** [comment]
Some people had problems with this: 
- #916
- #849
- #880 :wink:

**Comment by StefMa** [comment]
Oh, myself. Please merge! 😂

**Comment by larsgrefer** [comment]
@hzsweers i've fixed the code formatting

**Comment by fadils** [comment]
Alright. Hopefully, people will no longer ask about 404 error.
Thanks!

**Pull request merged**
