### PR TITLE
Support filtering the repositories page list

### PR DESCRIPTION
**Pull request by fadils**
Perhaps, next step is to create something like a quick-return for both the filter box and the toolbar? Because, now when user types something, the screen is really, really tight.

### CODE REVIEW

**Comment by fadils** [comment]
Any input regarding this?

cc: @jonan @hzsweers @larsgrefer

**Comment by larsgrefer** [comment]
I think it would be better to add a menu-entry (action-button) for the filtering feature.
So the input-field can be shown or hidden like the searchbar

**Comment by hzsweers** [comment]
@fadils let's get this in, but maybe update the PR with more details information. Specifically, screenshots and an overview of the changes would be especially useful if everything is going to be squashed into one commit.

**Comment by fadils** [comment]
Will do

**Comment by Meisolsson** [comment]
Closing for inactivity

**Pull request closed without merging**
