### PR TITLE
News redesign

### PR DESCRIPTION
**Pull request by veyndan**
Related to #1120.

The avatar and the bold parts of the news item titles are clickable (except from the branch name). The branch name isn't clickable due to the architecture of the app, and such an implementation couldn't be done easily as of yet. This isn't to say that the branch shouldn't be clickable in the future.

Because these things are clickable, long pressing the item to navigate to the user name or repository page is unnecessary so it was removed.

|Before|After|
|---|---|
|before|after|

### CODE REVIEW

**Comment by Meisolsson** [comment]
I'm gonna try this out for a while but from first impressions I'm not sold. Feels like a cluttered screen and I also think that those touch targets are to small, I know it's text but it's now also a target for interaction.

**Comment by veyndan** [comment]
I feel like the cluttering of the screen is more to do with the design, i.e. having the links underlined and being such a vibrant blue. Maybe we can get rid of the blue styling for the username as it's unnecessary when you know you can click the avatar as well.

As with the target interaction, I don't feel that's a problem. If you look at Instagram with their hashtags, they have a similar touch target size and they don't seem to have a problem.

**Comment by Meisolsson** [comment]
Regarding Instagram that's not one of their main navigation sources. That's content links just like we have in comment bodies. At least that's how I see them.

**Comment by veyndan** [comment]
How about Facebook then? They have a similar style where the title and the comment bodies have content links.

image

**Comment by Meisolsson** [comment]
Aight, been using it a bit over the last couple of weeks. It's been easier to click the text when it's close together than I expected so that's nice. I'm still not sold on it though. Do some more work on the design and I'll have another look.

**Comment by veyndan** [comment]
I've removed the underline from the links. I've left the link color as it is just using the accent color which I believe is semantically correct. Admittedly the color combination between the toolbar and link color isn't great (i.e. primary and accent color), but that is related to #1225, not this PR.

|Initial design|Final design|
|---|---|
|before|after|

**Comment by fadils** [comment]
In my opinion, I think this is pretty good.
And, I'm more than glad to merge it.

**Comment by veyndan** [comment]
Thanks @fadils! I'd love to see this get merged as I think it is a step in the right direction for UX.

**Pull request merged**
