### PR TITLE
 "log out" feature in the navigation drawer

### PR DESCRIPTION
**Pull request by Yuliya-Kaleda**
I added a log out feature in the navigation drawer to make it easy for users to access. Through shared preferences I save and  keep track of  the user's activity state (either logged in or out) to make sure that the log out process gets validated when the user leaves the app and launches it again later.

### CODE REVIEW

**Comment by hzsweers** [comment]
Can you add a screenshot to the PR?

**Comment by Yuliya-Kaleda** [comment]
image

**Comment by Yuliya-Kaleda** [comment]
log_out 2

**Comment by Meisolsson** [comment]
Would the better way of doing this not be removing the account? Since we might add multi account support later on (I have some plans for that).

**Comment by Yuliya-Kaleda** [comment]
Adding a multi account support may be a great idea if there is a decent amount of people who have more than one account (although as a user I can say that there is no much sense to create separate accounts since there is an option to create private repos and organizations, which deliver the same function as separate "accounts"). But in the long run ( whether it is single or multi account support) it is of great importance for users to have easy access to "log out" when they don't want to leave account open on certain devices.

**Comment by Meisolsson** [comment]
Well instead of adding a preference you can use http://developer.android.com/reference/android/accounts/AccountManager.html#clearPassword(android.accounts.Account) and later we can update the password. This way we dont's save the user credentials.

**Comment by Yuliya-Kaleda** [comment]
sounds like a great idea. Would you like me to refactor the code using clearPassword?

**Comment by Meisolsson** [comment]
Well i think you should wait until we have implemented the new auth/login system. 
On Jun 29, 2015 5:28 PM, Yuliya Kaleda <notifications@github.com> wrote:sounds like a great idea. Would you like me to refactor the code using clearPassword?

**Comment by hzsweers** [comment]
I agree. We have a PR open for that right now, so hopefully we'll have that
in master in the next couple of days. Would you mind waiting until then,
and then rebasing before refactoring?

**Comment by Yuliya-Kaleda** [comment]
no, I can definitely wait.

**Comment by hzsweers** [comment]
Cool, we'll let you know when the other PR is in.

**Comment by Yuliya-Kaleda** [comment]
Thank you!

**Comment by hzsweers** [comment]
Just wanted to say we didn't forget about this, just have hit a snag with the new authentication API and are currently trying to get it resolved with github

**Comment by Yuliya-Kaleda** [comment]
Thank you for keeping me updated.

**Comment by Meisolsson** [comment]
This can be added now, since we don't use a password you would need to use the AccountManager.setAuthToken and give it null. I think that should trigger a login

**Comment by Yuliya-Kaleda** [comment]
I pulled the recent code to work on the log out feature for the app. When I press the log in button and put in my password, I see 404 with a message "Didn't find anything".

**Comment by Yuliya-Kaleda** [comment]
image

**Comment by Yuliya-Kaleda** [comment]
img_2129

**Comment by Meisolsson** [comment]
See #845

**Comment by hzsweers** [comment]
@Yuliya-Kaleda were you able to get it working?

**Comment by Yuliya-Kaleda** [comment]
@hzsweers I have some of my projects going on... August is pretty busy. I am sorry, I did not have time to look at the app after I sent you a message about 404 error. How urgent is it? I do plan to work on it later.

**Comment by hzsweers** [comment]
We're looking at probably doing a release after this pull request, since we don't have any other outstanding ones open right now. If you're too busy though, I can manually take care of it and finish it myself.

**Comment by Yuliya-Kaleda** [comment]
ok, I planned to work on it in a couple weeks, but if you cannot wait, I don't mind you finishing it. Please let me know if you need any help!

**Comment by hzsweers** [comment]
Cool, I'll take care of it and let you know if I run into any problems!

**Comment by fadils** [comment]
I've continued this and, it works fine now.
Now, how do you guys want to approach this @hzsweers  @Meisolsson ?

1. Should I merge directly to master?
2. Create a new branch, and make a PR off of there?
3. ?

I can also make a PR against @Yuliya-Kaleda master. But not sure about this.

**Comment by hzsweers** [comment]
New branch and PR

**Comment by ChunxiaZhang** [comment]
After log out, open app, click login button, enter account directly. It seems the account didn't really delete, only token was delete.

**Comment by fadils** [comment]
@ChunxiaZhang that's what a log-out is.
You don't delete the account.

**Comment by ChunxiaZhang** [comment]
@fadils Then how to use another account to login?

**Comment by fadils** [comment]
@ChunxiaZhang not yet supported. 

cc: @Meisolsson

**Pull request merged**
