### PR TITLE
Added padding between avatar and titles in toolbar #983

### PR DESCRIPTION
**Pull request by kubaspatny**
Fixing  #983, where there was previously no space between the icon and titles.

Added 8dp padding between the avatar and the titles in Toolbar.

Previously:

before

Now:

now

### CODE REVIEW

**Comment by hzsweers** [comment]
One nit, rest looks good!

**Comment by kubaspatny** [comment]
Oh right, didn't see that. I will revert it and update tomorrow, thanks!

**Comment by kubaspatny** [comment]
The problem was actually that material dialogs resolved the new Support Library version 23.2.0, which started using vector resources and removed the `abc_ic_menu_share_mtrl_alpha` resource, replaced by vector resource `abc_ic_menu_share_material`.

More info:
http://android-developers.blogspot.cz/2016/02/android-support-library-232.html
http://stackoverflow.com/questions/35628572/update-support-library-23-2-0-build-bug/35628668

**Comment by hzsweers** [comment]
Thanks!

**Pull request merged**
