### PR TITLE
Braces are used where optional

### PR DESCRIPTION
**Pull request by veyndan**
As [Google's Java Style Guide](https://google.github.io/styleguide/javaguide.html) is now being used for this project, [braces are used where optional](https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used).

### CODE REVIEW

**Comment by veyndan** [comment]
I thought that by default Travis fails when rules are violated again, or is the wrong?

Also come to think of it, I guess if someone is working on a separate change, then the merge conflicts of this PR would be pretty annoying (albeit easy to fix).

**Comment by larsgrefer** [comment]
@veyndan Travis fails only when `./gradlew clean build` fails.

**Comment by veyndan** [comment]
I understand now thanks, so do you think it'd be better to just set [this line](https://github.com/pockethub/PocketHub/blob/master/script/style/checkstyle.xml#L25) to have a severity of `error`?

**Comment by larsgrefer** [comment]
@veyndan The line you linked above affects all checkstyle rules. Once all violations are resolved, this line should be set to `error`, but setting this to `error` now would force you to fix all violations now.

**Comment by larsgrefer** [comment]
@veyndan Have a look at https://github.com/veyndan/PocketHub/pull/2

**Comment by Meisolsson** [comment]
I think it's better to wait and set the severity to error for all at once.

**Pull request merged**
