### PR TITLE
Moved to new SDK

### PR DESCRIPTION
**Pull request by Meisolsson**
Alright, basically the old SDK in deprecated/not maintained so I have there for developed and implemented a new [SDK](https://github.com/Meisolsson/GitHubSdk). 

The new SDK only uses the stable API features, for now.

### CODE REVIEW

**Comment by hzsweers** [comment]
I'm just gonna say #yolo on this. A little too hard to review in its current state, so let's just role with this

**Comment by Meisolsson** [comment]
Aight

**Comment by Meisolsson** [comment]
@hzsweers Should we roll out a release as well?

**Comment by hzsweers** [comment]
Up to you, I'm pretty removed at this point. I don't see an issue with releasing often though

**Pull request merged**
