### PR TITLE
Several enhancements regarding network problems

### PR DESCRIPTION
**Pull request by stream101**
Tested in offline and 3G network: 
a. check connectivity before login, and show error message if no connection;
b. if list loader fails, and it is caused by no network, show "no internet connection" to give user better error message;
c. the default okhttp timeout is too short for slow network. Increase the timeout value and also retry on connection failure.

### CODE REVIEW

**Comment by hzsweers** [comment]
Commented with some nits

**Comment by stream101** [comment]
Comments addressed.

**Comment by hzsweers** [comment]
Let's resolve those merge conflicts and get rid of the merge commit please

**Comment by hzsweers** [comment]
Ping for updates

**Comment by Meisolsson** [comment]
Closing for inactivity

**Pull request closed without merging**
