### PR TITLE
Add settings activity

### PR DESCRIPTION
**Pull request by larsgrefer**
Not ready to merge yet. 
I just want to start sharing my ideas about this, get a discussion going and collect ideas.

Things i'd like to add:
- Icons for Preference-Elements
- *Report a bug*-Element

Maybe:
- *View/Fork us on github*-Element
- *Open Source Licenses*-Element

The first draft:
screenshot_20151015-000721

### CODE REVIEW

**Comment by larsgrefer** [comment]
related to #66

**Comment by StefMa** [comment]
It would be cool if we can manage the github account.
Like https://github.com/settings/profile to change:
* Avatar
* Name
* URL
* Company
* Location
* Password
* Username
* Change/Add E-Mails

etc.

**Comment by fadils** [comment]
@larsgrefer how is it going?

**Comment by larsgrefer** [comment]
@fadils waiting for #939 being fixed, because the **report a bug** feature is pretty useless otherwise

**Comment by fadils** [comment]
Are you saying that you're holding the whole setting feature because one part of setting can't be done?

**Comment by larsgrefer** [comment]
- The "report a bug" feature is implemented and already present in this PR, but it is not working.
- The icons aren't implemented yet, because I was waiting for a stable version `com.android.tools.build:gradle:1.4.x` (because of the automatic vector -> `png` conversion)

If you'd like to merge this, feel free to do so.

**Comment by StefMa** [comment]
Gradle build tools plugin 1.5 is available :-)
Am 19.11.2015 10:05 nachm. schrieb "Lars Grefer" <notifications@github.com>:

**Comment by larsgrefer** [comment]
@StefMa I have just noticed that too. 
1.4x is still beta, but 1.5.0 is released

**Comment by larsgrefer** [comment]
@StefMa I've implemented the icons

**Comment by larsgrefer** [comment]
screenshot_20151121-180223

**Comment by StefMa** [comment]
Is this really a settings page or more a about (or something) page? :-)
See not a single setting here...
Am 21.11.2015 6:05 nachm. schrieb "Lars Grefer" <notifications@github.com>:

**Comment by larsgrefer** [comment]
Its a settings activity with only one category. More categories can be added in the future

**Comment by fadils** [comment]
Could you please add those setting categories in this PR as well?

**Comment by fadils** [comment]
@larsgrefer any chance to add those setting?

**Comment by larsgrefer** [comment]
@fadils At the moment im working on the profile settings mentioned by @StefMa

**Comment by fadils** [comment]
Alright..

**Comment by andrewlord1990** [comment]
If you look at the Material Design spec for settings pages:

https://www.google.com/design/spec/patterns/settings.html#settings-grouping-settings

It suggests having settings grouped based on how many settings there are. I wouldn't have icons on the options unless it helps make the settings easier to understand or to find them quicker. I.e. when someone is looking for sound settings a speaker icon can really help.

Therefore, often you only see icons when it is the root page of settings with different groups on it (like in the stock Android settings app). Unless you have a lot of different settings, this top-level group page wouldn't be required.

So in the example above I personally, don't think icons are required for version and build. I would have Report a bug with an icon as the top option (not under a section header). Then, under About I would have the other two. The about section would move down when other settings sections are added, as things that are actually settings will probably be more regularly used by users.

**Comment by hzsweers** [comment]
I agree. I'm actually going to close this for now seeing as it never got anywhere. We can revisit in the future if and when more settings use cases arise

**Pull request closed without merging**
