### PR TITLE
adjust icon alignment on api 23

### LINKED ISSUE #929: Unaligned Icons on API 23
On my Nexus 5 with Android 6.0 the top of some icons is cut-off

(the icons left of `Vor 2 Stunden`)

screenshot_20151012-214632

### PR DESCRIPTION
**Pull request by larsgrefer**
fixes #929 

I've copied the icon-styles to `values-v23`, set `android:layout_marginTop` to `0dp` and replaced `android:layout_height` with `android:maxHeight`

### CODE REVIEW

**Comment by Meisolsson** [comment]
Have you tested changing the font size on the phone? (The icons scale with that)

**Comment by larsgrefer** [comment]
Yes, API 23 with normal font size looks good, and API 23 with extra large font size looks good, too.

**Comment by Meisolsson** [comment]
Alright was just thinking about the max_height that was set, but seems to work. Thanks!

**Comment by larsgrefer** [comment]
Switching `height` to `maxHeight` just allows the icon to become smaller if possible (the inherited value for `height` is `wrap_content`)

**Pull request merged**
