### PR TITLE
fixed broken tests

### PR DESCRIPTION
**Pull request by StefMa**
I've fixed the broken junit test (which I'm also migrated to a robolectric test) becuase of the new Github API.
#hacktoberfest

### CODE REVIEW

**Comment by StefMa** [comment]
@fadils  @hzsweers whats going on here? :o
How can I fix this? Have created a github.properties like descripted [here](https://github.com/pockethub/PocketHub#setup-environment)

**Comment by larsgrefer** [comment]
Travis tries to decrypt the github.properties.enc file using two secure environment variables, but on pull requests those variables aren't set by travis

**Comment by larsgrefer** [comment]
#885 Should fix the travis problems

**Comment by larsgrefer** [comment]
fixes #881

**Comment by fadils** [comment]
@StefMa we'll take a look into it. Thanks for PR!

**Comment by larsgrefer** [comment]
I've tested the changes on my local machine:
```$ ./gradlew clean build```
```
BUILD SUCCESSFUL

Total time: 1 mins 38.036 secs
```

**Comment by StefMa** [comment]
That's not all lars.
testing is also `SUCCESSFUL`
`$./gradlew testDebug`

````
BUILD SUCCESSFUL

Total time: 12.396 secs
````
Ok joking aside. I think we can merge it ;)

**Comment by larsgrefer** [comment]
The ```:build```-task includes ```:check``` which includes ```:test``` :stuck_out_tongue_winking_eye: 

I agree on merging this one :+1:

**Comment by fadils** [comment]
Thanks guys!

**Pull request merged**
