### PR TITLE
Create gist refactoring

### PR DESCRIPTION
**Pull request by StefMa**
I've made some refactoring of the gitst_create xml file.
There is also an UI change. See here
before:

and after:

(See Title ;))

Did not get it do make the checkbox "better" on the left. Have any other an idea for that?

### CODE REVIEW

**Comment by karllindmark** [comment]
Hey @StefMa, just a pointer while you're refactoring - you could probably extract the inlined dimensions to `dimens.xml`. :-)

**Comment by StefMa** [comment]
Great idea @karllindmark 
I've moved the [touch target size to dimens.xml](https://github.com/pockethub/PocketHub/commit/cdfa895e3982e47843deddab1e6d1dc59357c830)
The rest, in my thoughts, can be contained in the xml because they aren't "default" values so that they stored "globale".

**Comment by StefMa** [comment]
@fadils @larsgrefer is this PR ok? Or not?
Btw: Who can already merge PR's? Only @fadils ?

**Comment by Meisolsson** [comment]
Why did you remove the hints? Other than that it looks good

**Comment by StefMa** [comment]
Because they wasn't 'in use'. They were white on white so not visible. They aren't used in the fragment too. So I've cleaned it up :-)

**Comment by larsgrefer** [comment]
@StefMa Please rebase your branch against the current master, so travis can run properly.

**Comment by larsgrefer** [comment]
I think we should keep the hints. Once we move to [`TextInputLayout`](http://developer.android.com/reference/android/support/design/widget/TextInputLayout.html) we will need them.

I will solve the white-on-white problem will be solved by #896

**Comment by larsgrefer** [comment]
@StefMa pull requests can be merged by @fadils, @jonan or @Meisolsson

**Comment by StefMa** [comment]
rebase means merging the current master in to one?!

#896 have nothing to do with the hint color.
We can change this with 
```
style="@style/AppCompatOverlay.Light" 
```
or 
```
android:textHintColor="@color/black"
```
So the hint will be go dark.

Currently we aren't on TextInputLayout. So this isn't currently a requiement to "save" the hints.
They were also a little bit.. ugly?! :-1: 
I mean: https://github.com/StefMa/PocketHub/commit/7f5c36d6f2ae397aa0906c19f4a5f6cd4954b29a#diff-01dafb3fd0217441330103cfc8300094L118 & https://github.com/pockethub/PocketHub/blob/master/app/src/main/res/values/strings.xml#L153 & https://github.com/pockethub/PocketHub/blob/master/app/src/main/res/values/strings.xml#L120

**Comment by larsgrefer** [comment]
@StefMa rebase is not merging (http://git-scm.com/book/en/v2/Git-Branching-Rebasing).
Given you have 2 remotes `origin` (your fork: StefMa/PocketHub) and `upstream` (this repo: pockethub/PocketHub):
```bash
git checkout createGistRefactoring
git pull origin createGistRefactoring
git fetch upstream
git rebase -i upstream/master
git push -f origin createGistRefactoring
```

The main color problem is that `Theme.GitHub` has a dark theme as parent, so the default text-color is white. In #896 I changed the parent theme to the light one

**Comment by StefMa** [comment]
Rebased, travis is happy. Time to merge ;)

**Comment by Meisolsson** [comment]
Look good

**Pull request merged**
