### PR TITLE
#583 fixed

### PR DESCRIPTION
**Pull request by Meisolsson**
This fixes the issue of of issues not showing in the app

### CODE REVIEW

**Comment by gergelypolonkai** [comment]
Is this already released to the Play Store? I still have this issue and it's pretty annoying.

**Comment by Meisolsson** [comment]
Well the GitHub app us no longer maintained under GitHub so that app will not work. The ForkHub app on the other hand will that is also the app we will be maintaining!

**Comment by hzsweers** [comment]
Henrik it would be nice if you guys helped with this project now that
Github has turned it over to the community rather than continue forkhub.
It's just going to cause confusion.

I'm on vacation right now, but the plan was to release soon.

**Comment by Meisolsson** [comment]
Well was the plan not to release under the name ForkHub? (Have been away for a while)

**Comment by hzsweers** [comment]
No... This is not the same Forkub that @jonan has been maintaining, nor was
that the plan. This is to be the spiritual successor to the official github
app. Name is still undecided, doesn't really help that Kevin made the org
name "forkhubs".

**Comment by Meisolsson** [comment]
Alright good to know! Well I'm only contributing here so thats fine

**Pull request merged**
