### PR TITLE
Fix issue 997

### PR DESCRIPTION
**Pull request by frankFic**
This is a fix for issue #997.
Changed as recommended by @Meisolsson

### CODE REVIEW

**Comment by frankFic** [comment]
Build failed because of the old gradle version in build.gradle file of the project. Shall I update it to 2.0.0?

**Comment by Meisolsson** [comment]
Before you update that, do you have any way to test it. More specifically a Samsung device?

**Comment by frankFic** [comment]
I am sorry I didn't add that change to this commit because I only wanted to include the change related to this issue and was not sure if it is OK for me to change parts other than this.

**Comment by Meisolsson** [comment]
Didn't mean the Gradle change, I think we'll add that separately. What I meant was if you had any ability to test the ProGuard change on a Samsung device. As I don't have one and only have some data on the issue.

**Pull request merged**
