### PR TITLE
changed onAttach(Activity) to onAttach(Context)

### PR DESCRIPTION
**Pull request by StefMa**
Replaced all onAttach(Activity) to onAttach(Context) because first one is [deprecated](http://developer.android.com/reference/android/app/Fragment.html#onAttach(android.app.Activity)).

### CODE REVIEW

**Comment by larsgrefer** [comment]
looks good to me :+1:

**Comment by Meisolsson** [comment]
Would this not break on older devices since the call is added in api 23?

**Comment by larsgrefer** [comment]
@Meisolsson No, because Activity extends Context

**Comment by StefMa** [comment]
Have rebased the branch because of conflicts...

**Comment by Meisolsson** [comment]
Alright, looks good.

Thank you

**Pull request merged**
