### PR TITLE
Disable preDexing only on continuous integration systems

### PR DESCRIPTION
**Pull request by larsgrefer**

### CODE REVIEW

**Comment by larsgrefer** [comment]
travis fails because of #885

**Comment by larsgrefer** [comment]
@fadils @hzsweers any opinions about this?

**Comment by Meisolsson** [comment]
Why should we remove it only on CI?

**Comment by larsgrefer** [comment]
>`boolean preDexLibraries`
>Whether to pre-dex libraries. This can improve incremental builds, but clean builds may be slower.

(http://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.DexOptions.html#com.android.build.gradle.internal.dsl.DexOptions:preDexLibraries)

The default value is `true`

**Comment by larsgrefer** [comment]
@StefMa @fadils Whats your opinion?

**Comment by StefMa** [comment]
I see currently no significant changes (faster building) for this PR. But maybe my Dev machine is fast enough? ;-)
Ok joke aside. 
When this change makes some some machines faster on building (and so in developing) why not?

**Comment by larsgrefer** [comment]
@StefMa Lets add a few numbers (tested on my mac book air with os x el capitan, 4GB RAM and 1,4GHz i5):
- without preDex (current master):
  - `clean assemble`: 1 mins 19.054 secs
  - next `assemble`: 1 mins 9.904 secs
- with preDex (android default)
  - `clean assemble`: 1 mins 37.937 secs
  - next `assemble`: 34.528 secs

@Meisolsson as you can see a clean build is a little bit slower, so we disable preDex on travis, because travis performs only clean builds.
Subsequent builds during development are much faster with preDex.

**Comment by larsgrefer** [comment]
@hzsweers What's your opinion?

**Comment by larsgrefer** [comment]
No new opinions?

**Comment by hzsweers** [comment]
Done on master already, didn't see this PR

**Pull request closed without merging**
