### PR TITLE
Create and include keystore

### PR DESCRIPTION
**Pull request by larsgrefer**
Add release keystore as mentioned in #872 

The certificate is 1000 years valid and protected by a 20 characters long password

On travis we can set the environment variable `ORG_GRADLE_PROJECT_pockethub_keystore_password` in order to provide the password

### CODE REVIEW

**Comment by Meisolsson** [comment]
Keystone will be created by us when we need it

**Comment by larsgrefer** [comment]
@Meisolsson could you explain whats wrong with my keystore?

**Comment by Meisolsson** [comment]
Nothing, but we don't need it for the moment and I think we want the password to be secret to the organization.

**Comment by hzsweers** [comment]
Agreed, this is something that should only be known by org members and not public.

**Pull request closed without merging**
