### PR TITLE
SDK change/update

### PR DESCRIPTION
**Pull request by Meisolsson**
Since we talked about it in #792 I migrated the app to the GithubAndroidSdk.Some things might crash since I haven't tested all of it, but it should mostly work.

### CODE REVIEW

**Comment by fadils** [comment]
Was half-done reviewing. I think this is awesome!

Was wondering if we can make all API client into a Singleton instead of calling a `new GetGitWhateverClient`.

Thoughts?

**Comment by Meisolsson** [comment]
I like the idea but then the lib needs a couple of updates. We can talk to him about it and see it he likes the idea.
On Sep 25, 2015 04:34, Fadil Sutomo <notifications@github.com> wrote:Was half-done reviewing. I think this is awesome!

Was wondering if we can make all API client into a Singleton instead of calling a new GetGitWhateverClient.

Thoughts?

**Comment by fadils** [comment]
What about extending the clients, then put them in a Singleton for each?

**Comment by alorma** [comment]
What you need to use with Singleteon? And why?

**Comment by Meisolsson** [comment]
Well that won't work since you give the info when creating a new instance
On Sep 25, 2015 10:30 AM, Fadil Sutomo <notifications@github.com> wrote:What about extending the clients, then put them in a Singleton for each?

**Comment by fadils** [comment]
Yup, just looking into the details now. Just realize, it's different kinda thing. Alright.

**Comment by Meisolsson** [comment]
And @fadils why don't we add the github.properties values as Travis environment variables (they can be hidden in the build log) instead of having them encrypted?

**Comment by fadils** [comment]
Yes.. you can do that and just change the current one

**Comment by Meisolsson** [comment]
I'll do that after this is good. Just so we keep them sperate.

**Comment by fadils** [comment]
LGTM. Additional input from @hzsweers perhaps?

**Comment by hzsweers** [comment]
Looks good to me. Hard to make a full analysis up front for this many changes, so I think it's better we just get this in and iterate on it from there

**Comment by fadils** [comment]
@Meisolsson you can now push changes in `github.properties` for Travis.

**Pull request merged**
