### PR TITLE
Redesigned Issue Header

### PR DESCRIPTION
**Pull request by StefMa**
I've redesigned the Header in Issues.
Pictures says more than thousand words:
Old:

New:

.. And more new stuff :D
(Open with Labels)

(Closed)

I've tried to copy the issue "layout" from github.com but removed open/closed label and the issue number (displayed already in toolbar :))

Any thoughts?

### CODE REVIEW

**Comment by Meisolsson** [comment]
I really dislike the toolbar, looks weird with two titles (Issue title and the "Issue #123"). Not sure how to change it :/

**Comment by StefMa** [comment]
Yep I don't like the toolbar as well. But that wasn't the change 😊
If you like my changes I suggest that we merge that and I will look in to the toolbar in another PR...

**Comment by Meisolsson** [comment]
Well the header is what makes the toolbar look ugly. So that's the problem

**Comment by StefMa** [comment]
Ah OK. That's what do you mean... 
Don't know if it will work. But what do you think about to move the issue number behind the title (exactly like the web) and just set the toolbar title to the repository name?!

**Comment by StefMa** [comment]
What do you think about that?

**Comment by StefMa** [comment]
I've rebased it. Update your local branch...

**Comment by Meisolsson** [comment]
How about just making the header a CollapsingToolbar, like this for example: 

Example image

When the toolbar is expanded the title is the issue title. And when it collapses we set the toolbar title to something like <code>#{Issue number}</code> with the issue info as a subtitle (Who opened, when was it opened etc.) Sounds good?

**Comment by StefMa** [comment]
Sry but the code is just a mess. If you take a look in it it can't be happen with some small changes. I don't want to write the whole classes from scratch (which is needed when we make a CollapsingToolbarLayout). So that's why it looks like it looks :-D

**Comment by Meisolsson** [comment]
Well someone's gonna end up rewriting it later anyway so the best is to do it now. I don't really like the way this looks. 

I'll think about it a bit more but I would prefer having the collapsing toolbar

**Comment by hzsweers** [comment]
The collapsing header looks great, would probably be better to start the migration here

**Comment by Meisolsson** [comment]
@hzweers So you think we should merge this? A bit confused about "collapsing header".

**Comment by hzsweers** [comment]
No I agree with you, I think the current state of this PR doesn't look that great, and would rather go the whole nine yards

**Comment by Meisolsson** [comment]
Alright, with that I'm closing this. I'm also gonna open a new issue so we can discuss this deeper.

**Pull request closed without merging**
